apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-monitor-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeName: app-monitor-data  # binds directly to the named PV above
